import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const noteBookSidebars: SidebarsConfig = {
  noteBookSidebars: [{ type: 'autogenerated', dirName: '.' }],
};

export default noteBookSidebars;
