import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const edgeExtensionSidebars: SidebarsConfig = {
  edgeExtensionSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: 'edge 扩展页',
      href: 'https://microsoftedge.microsoft.com/addons/search?developer=lmssee',
    },
  ],
};

export default edgeExtensionSidebars;
