import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const npmSidebars: SidebarsConfig = {
  npmSidebars: [{ type: 'autogenerated', dirName: '.' }],
};

export default npmSidebars;
