import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const npmSidebars: SidebarsConfig = {
  // npm: [{ type: 'autogenerated', dirName: '.' }],
  npmSidebars: [
    'nry',
    'gvv',
    'jja',
    'colored-table',
    'create-a-npm',
    {
      type: 'category',
      label: 'qqi',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'qqi/index',
      },
      items: [
        'qqi/core',
        'qqi/check-version',
        'qqi/remove-dog',
        'qqi/copy-text',
        'qqi/dev',
      ],
    },
    {
      type: 'category',
      label: 'a-command',
      collapsible: true,
      //     type: "generated-index";
      // slug?: string;
      // title?: string;
      // description?: string;
      // image?: string;
      // keywords?: string | readonly string[];
      link: {
        type: 'doc',
        id: 'a-command/index',
      },
      items: ['a-command/args', 'a-command/question', 'a-command/selection'],
    },
    'a-node-tools',
    'color-pen',
    'a-js-tools',
    'a-type-of-js',
    'pjj',
    'index',
  ],
};

export default npmSidebars;
